### ISSUE TITLE
UART data command 

### ISSUE THREAD

**Issue by thangta** [HomeACcessoryKid/AQARA-ZNCLDJ11LM#1]
Could you share the uart data command between EPS8266 and AT Mega. I see some MODBUS data in main.c   but I not sure
Thanks.

**Comment by HomeACcessoryKid** [comment]
It is not real modbus but some engineer who didn’t really understand it making something up (IMHO)

BR,
HacK

**Comment by thangta** [comment]
I see "//hardcoded CRC16_MODBUS" comment in main.c.  At calibrate_task function, you send this command directly to uart. I also try to send same commands, but nothing change in aqara motor. I working on another MCU instead ESP. 

P/S: could you please to share how to quickly make motor working.

**Comment by HomeACcessoryKid** [comment]
Hopefully images I add to this mail-reply will come in the answer, if not, I will delete the answer and find another way to convey the info (eventually)
This is a pair of screenshots of a TRACE I made on the serial port while the official app of aqara was doing control after power up.
You should be able to match this with the code and work out things from there...
I will not elaborate on this more, too many other things to do…

**Comment by HomeACcessoryKid** [comment]
I have added a page to the Wiki
As for styles of coding, I like to cut corners if they make sense to me during development, but feel free to do things differently. I am not in it for the 'perfect coding award'.

MAYBE there is something going on with the BAUDRATE.  MY motor sends out a reset command at 19200 baud but after that all is done at 9600 baud. Maybe your motor is at 19200 baud all the time?
